# Generated by Django 6.1 on 2026-08-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('duracao', models.PositiveBigIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
