# Generated by Django 6.1 on 2026-08-17 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(default='confirmado', max_length=20)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.servico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('barbeiro', 'data', 'horario'), name='unique_agendamento_barbeiro_data_horario')],
            },
        ),
    ]
