# Generated by Django 6.1 on 2026-08-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agendamento_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='unique_agendamento_barbeiro_data_horario',
        ),
    ]
